-- MycoMaps seed data — REAL verified retailers (generated 2026-05-25)
-- Source of truth: data/retailers/{therapeutic,colorado,online}.ts (see those files for provenance).
-- Regenerate with: npx tsx scripts/gen-seed.ts
-- WARNING: Truncates retailers table before inserting.
TRUNCATE TABLE retailers CASCADE;

INSERT INTO retailers (slug, name, description, verticals, address, city, state, zip, lat, lng, phone, website, email, hours, cover_url, photo_urls, is_verified, verification_type, subscription_tier, avg_rating, review_count) VALUES
(
  'the-center-origin', 'The Center Origin', 'A licensed psychedelic-assisted healing center in LoDo Denver specializing in journey work, natural medicine services, post-journey integration, and facilitator training. Reported as Colorado''s first state-licensed psilocybin healing center.',
  ARRAY['therapeutic'],
  '1440 Blake Street, Suite 330', 'Denver', 'CO', '80202',
  39.7490933, -105.0008779,
  '3032844246', 'https://www.thecenterorigin.com', NULL,
  '{"mon":"By appointment","tue":"By appointment","wed":"By appointment","thu":"By appointment","fri":"By appointment","sat":"By appointment","sun":"By appointment"}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-attested "Licensed Natural Medicine Healing Center" on thecenterorigin.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center); reported as Colorado''s first state-issued healing center license (CPR, 2025-03-31).', 'basic',
  0, 0
),
(
  'happy-rebel-healing', 'Happy Rebel Healing', 'A Colorado state-licensed Natural Medicine healing center in Boulder offering individual and group psilocybin sessions and support in a professionally guided setting.',
  ARRAY['therapeutic'],
  '3450 Penrose Place, Suite 220', 'Boulder', 'CO', '80301',
  40.037452, -105.247479,
  '7208009119', 'https://www.happyrebelhealing.com', 'teresa@happyrebelhealing.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "Colorado state-licensed Natural Medicine Healing Center" on happyrebelhealing.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'chariot-psilocybin-healing-center', 'Chariot', 'A psilocybin service center offering guided psilocybin-assisted sessions in a curated, supervised space with licensed facilitators. Operates a Boulder, Colorado location (also Portland, OR).',
  ARRAY['therapeutic'],
  '1240 Pine St', 'Boulder', 'CO', '80302',
  40.0198523, -105.279461,
  NULL, 'https://chariotspace.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center) with the 1240 Pine St Boulder address matching chariotspace.com; reported as an operating Boulder healing center (Axios Boulder, 2025-12-01).', 'basic',
  0, 0
),
(
  'psychedelic-growth', 'Psychedelic Growth', 'A Boulder healing center providing psychedelic-assisted therapy with licensed facilitators, including psilocybin, structured around preparation, the session, and integration.',
  ARRAY['therapeutic'],
  '5277 Manhattan Circle, Suite 103', 'Boulder', 'CO', '80303',
  39.9850601, -105.2294517,
  '7204413992', 'https://psychedelicgrowth.net', 'erin@psychedelicgrowth.net',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center); reported as an operating Boulder healing center (Axios Boulder, 2025-12-01). Note: own /contact page address (5277 Manhattan Circle) differs from HAF listing (3015 47th St); own-site value used.', 'basic',
  0, 0
),
(
  'wholeness-center', 'Wholeness Center', 'An integrative mental-health clinic in Fort Collins that describes itself as a licensed healing center offering psilocybin-assisted therapies alongside psychiatric and functional-medicine care.',
  ARRAY['therapeutic'],
  '2620 E Prospect Rd, Suite 190', 'Fort Collins', 'CO', '80525',
  40.5687254, -105.0280663,
  '9702211106', 'https://www.wholeness.com', 'info@wholeness.com',
  '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"9:00-13:00","sun":null}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "licensed healing center offering psilocybin-assisted therapies" on wholeness.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'numia-healing', 'Numia Healing', 'A Denver healing center offering legal, therapist-guided psilocybin-assisted therapy in a clinically structured setting for individuals, couples, and small groups, emphasizing preparation, safety, and integration.',
  ARRAY['therapeutic'],
  '75 S Madison St, Suite 201', 'Denver', 'CO', '80209',
  39.7150043, -104.946276,
  '7203727137', 'https://numiahealing.com', 'info@numiahealing.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described provider of "Legal, Therapist Guided Psilocybin-Assisted Therapy In Denver" on numiahealing.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'transcendent-integrative-health', 'Transcendent Integrative Health', 'An Arvada healing center providing psychedelic-assisted therapy at a licensed natural-medicine facility with on-site mushroom cultivation and licensed facilitators.',
  ARRAY['therapeutic'],
  '5511 W 56th Ave, Unit 100', 'Arvada', 'CO', '80002',
  39.7989895, -105.0560705,
  '3038287473', 'https://www.transcendent.health', 'info@transcendent.health',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "fully licensed" healing center "operating in alignment with Colorado law" on transcendent.health; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'sanctum-aspen', 'SANCTUM', 'An Aspen healing center offering legal, licensed, and medically supervised psilocybin retreats and natural-medicine services for adults 21+, with a focus on leadership and group transformation.',
  ARRAY['therapeutic'],
  '535 E Hyman Ave, Lower Level', 'Aspen', 'CO', '81611',
  39.1884328, -106.817777,
  '9702391147', 'https://www.sanctumaspen.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "legal, licensed, and medically supervised" Colorado healing center on sanctumaspen.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'vivid-minds-wellness', 'Vivid Minds Wellness', 'A Denver healing center offering guided psilocybin journeys along with yoga, breathwork, and art therapy in small groups. Describes itself as one of Colorado''s first licensed healing centers.',
  ARRAY['therapeutic'],
  '1545 S Broadway', 'Denver', 'CO', '80210',
  39.6885671, -104.9876124,
  '7202106553', 'https://vividmindswellness.com', NULL,
  '{"mon":"8:00-18:00","tue":"8:00-18:00","wed":"8:00-18:00","thu":"8:00-18:00","fri":"8:00-18:00","sat":"8:00-18:00","sun":"8:00-18:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'CO Natural Medicine healing center license # NMHC-00003 (published on vividmindswellness.com, "One of Colorado''s First Licensed Healing Centers"); also listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'neurobloom-aspen', 'NeuroBloom (Aspen)', 'A licensed Colorado healing center offering psychedelic / natural medicine services at its Aspen location (part of NeuroBloom, with a second location in Basalt).',
  ARRAY['therapeutic'],
  '426 E Main St, #1A', 'Aspen', 'CO', '81611',
  39.1906682, -106.8188121,
  NULL, 'https://neurobloompsychedelic.com', 'neurobloom@theneurospa.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "A licensed healing center with locations in Aspen and Basalt, Colorado" on neurobloompsychedelic.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'neurobloom-basalt', 'NeuroBloom (Basalt)', 'A licensed Colorado healing center offering psychedelic / natural medicine services at its Basalt location (part of NeuroBloom, with a second location in Aspen).',
  ARRAY['therapeutic'],
  '350 Market St, #001', 'Basalt', 'CO', '81621',
  39.3857934, -107.0836201,
  NULL, 'https://neurobloompsychedelic.com', 'neurobloom@theneurospa.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "A licensed healing center with locations in Aspen and Basalt, Colorado" on neurobloompsychedelic.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'aletheia-healing-center', 'Aletheia Healing Center', 'An Aspen healing center offering psilocybin facilitation under Colorado''s Regulated Natural Medicine Health Act, led by a Colorado Licensed Clinical Facilitator (also offers ketamine facilitation).',
  ARRAY['therapeutic'],
  '111 Aspen Airport Business Center, Suite K', 'Aspen', 'CO', '81611',
  39.1911128, -106.82356,
  NULL, 'https://aletheiahealingcenter.com', 'returntoyou@proton.me',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'CO Licensed Healing Center NMHC-00055 and Licensed Clinical Facilitator NMCF.0000019 (both published on aletheiahealingcenter.com); listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center). Coordinates are the Aspen 81611 centroid (full-street geocode unavailable).', 'basic',
  0, 0
),
(
  'the-clearing-boulder', 'The Clearing', 'A licensed psilocybin healing center in Boulder providing guided psilocybin-assisted sessions in a supportive setting.',
  ARRAY['therapeutic'],
  '1265 Yellow Pine Ave', 'Boulder', 'CO', '80304',
  40.059663, -105.2815328,
  '3035037800', 'https://theclearingboulder.com', 'adam@theclearingboulder.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "Licensed Psilocybin Healing Center in Boulder, CO" on theclearingboulder.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'emergence-psychedelic-therapy', 'Emergence Psychedelic Therapy', 'A licensed micro-healing center in Boulder operating within Colorado''s regulated Natural Medicine framework, where psilocybin is administered by a Natural Medicine clinical facilitator.',
  ARRAY['therapeutic'],
  '825 S Broadway, Suite 100', 'Boulder', 'CO', '80305',
  39.9766158, -105.2420837,
  '3035788845', 'https://psychedelictherapyco.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a licensed micro-healing center based in Boulder, Colorado, operating within Colorado''s regulated Natural Medicine framework" on psychedelictherapyco.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'sacred-peaks-retreat', 'Sacred Peaks Retreat', 'A Boulder-based state-licensed Natural Medicine Healing Center offering psilocybin mushroom facilitation.',
  ARRAY['therapeutic'],
  '134 Canon View Rd, Unit A', 'Boulder', 'CO', '80302',
  40.0738652, -105.3410755,
  '3038196528', 'https://sacredpeaksretreat.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a state-licensed Natural Medicine Healing Center through the Department of Revenue (DOR)" on sacredpeaksretreat.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center). Street address from HAF directory.', 'basic',
  0, 0
),
(
  'tlc-acupuncture-natural-medicine', 'TLC Acupuncture & Natural Medicine', 'A Breckenridge natural-medicine practice led by Dr. Tami L. Clark, a Colorado-licensed acupuncturist who holds Psilocybin Healing Center / Licensed Facilitator credentials.',
  ARRAY['therapeutic'],
  '101 N Main St, Unit 12', 'Breckenridge', 'CO', '80424',
  39.4823628, -106.0464778,
  '9704858801', 'https://tlcacu.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Own site (tlcacu.com) states Dr. Tami L. Clark holds "Psilocybin Healing Center/Licensed Facilitator" credentials; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center). Street address from HAF directory.', 'basic',
  0, 0
),
(
  'solaria-rising', 'Solaria Rising', 'A Broomfield natural-medicine healing center providing psilocybin / natural medicine services in accordance with Colorado Natural Medicine regulations.',
  ARRAY['therapeutic'],
  '80 Garden Center, Suite 310', 'Broomfield', 'CO', '80020',
  39.9234566, -105.0893961,
  '3038684548', 'https://solariarising.com', 'tonyasmithcounseling@gmail.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Own site (solariarising.com) states services are "provided through Solaria Rising (dba), a Natural Medicine Healing Center licensed and regulated by the Colorado Department of Revenue and the Natural Medicine Division"; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center). Street address from HAF directory.', 'basic',
  0, 0
),
(
  'river-soul-healing-center', 'River Soul Healing Center', 'A women-owned Denver healing center, newly state-licensed to provide psilocybin-assisted therapy within a Western therapeutic framework.',
  ARRAY['therapeutic'],
  '3773 Cherry Creek Dr N, East Tower, Ste 801', 'Denver', 'CO', '80209',
  39.6968607, -104.921913,
  '3037265072', 'https://riversoulhealingcenter.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Reported "newly licensed by the state to provide psilocybin-assisted therapy" (riversoulhealingcenter.com); listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'treehouse-sanctuary', 'Treehouse Sanctuary', 'A Denver healing center operating under Colorado''s Natural Medicine Health Act, offering natural-medicine services by appointment.',
  ARRAY['therapeutic'],
  '1600 N Pennsylvania St, Suite 300', 'Denver', 'CO', '80203',
  39.7418503, -104.9808389,
  NULL, 'https://treehousesanctuary.com', 'info@treehousesanctuary.com',
  '{"mon":"By appointment","tue":"By appointment","wed":"By appointment","thu":"By appointment","fri":"By appointment","sat":"By appointment","sun":"By appointment"}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a licensed Natural Medicine Healing Center operating under Colorado''s Natural Medicine Health Act (NMHA)" on treehousesanctuary.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'psychedelic-therapy-den', 'Psychedelic Therapy Den', 'A DORA-licensed Denver healing center providing psychedelic-assisted therapy under Colorado''s Proposition 122 natural-medicine framework, by appointment.',
  ARRAY['therapeutic'],
  '5335 W 48th Ave, Suite 602', 'Denver', 'CO', '80212',
  39.7841101, -105.054892,
  '3039270233', 'https://psychedelictherapyden.com', 'info@psychedelictherapyden.com',
  '{"mon":"By appointment","tue":"By appointment","wed":"By appointment","thu":"By appointment","fri":"By appointment","sat":"By appointment","sun":"By appointment"}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'CO healing center / facilitator references NMHC-00048 and NMCF-000017 published on psychedelictherapyden.com ("DORA-Licensed Healing Center," "100% Legal Under Prop 122"); listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'wild-glow-alchemy', 'Wild Glow Alchemy', 'A licensed Natural Medicine Healing Center in North Denver offering safe, supported psilocybin experiences.',
  ARRAY['therapeutic'],
  '8380 Zuni St', 'Denver', 'CO', '80221',
  39.7892588, -105.0158444,
  '7203369535', 'https://wildglowalchemy.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a licensed Natural Medicine Healing Center in North Denver" on wildglowalchemy.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center). Street address from HAF directory.', 'basic',
  0, 0
),
(
  'etc-hospitality', 'Etc Hospitality', 'A Golden, Colorado provider of natural-medicine journeys held with professional care.',
  ARRAY['therapeutic'],
  '16500 S Golden Rd, #105', 'Golden', 'CO', '80401',
  39.7354716, -105.1858884,
  '2162624445', 'https://etc-hospitality.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center); own site (etc-hospitality.com) is live and describes "Natural medicine journeys held with professional care." Street address from HAF directory.', 'basic',
  0, 0
),
(
  'go-within-collective', 'Go Within Collective', 'A Colorado Licensed Natural Medicine Healing Center in Lakewood whose licensed facilitators operate under the Natural Medicine Health Act.',
  ARRAY['therapeutic'],
  '1785 Kipling St, #8', 'Lakewood', 'CO', '80215',
  39.745354, -105.10968,
  '7202392225', 'https://gowithincollective.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "Colorado Licensed Natural Medicine Healing Center" on gowithincollective.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center). Street address from HAF directory.', 'basic',
  0, 0
),
(
  'neuroalchemy', 'NeuroAlchemy', 'A natural-medicine healing center in Littleton offering Natural Medicine services led by licensed clinical facilitators.',
  ARRAY['therapeutic'],
  '8500 W Bowles Ave, Ste 200', 'Littleton', 'CO', '80123',
  39.6111698, -105.0872198,
  '7202586111', 'https://neuroalchemycenter.com', 'info@neuroalchemycenter.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a natural-medicine healing center" offering "Natural Medicine services" on neuroalchemycenter.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'rose-healing-center', 'Rose Healing Center', 'A Lone Tree licensed medical clinic and collective of licensed clinical facilitators offering psilocybin-assisted therapy.',
  ARRAY['therapeutic'],
  '10450 Park Meadows Dr, Suite 100', 'Lone Tree', 'CO', '80124',
  39.5376248, -104.8737541,
  '7207076914', 'https://rosehealingcenters.com', 'info@rosehealingcenters.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a Colorado-based collective of licensed clinical facilitators devoted to offering psilocybin-assisted therapy" and "a licensed medical clinic" on rosehealingcenters.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'wild-roots-therapeutics', 'Wild Roots Therapeutics', 'A Salida practice offering psilocybin-assisted therapy alongside individual psychotherapy and ketamine-assisted psychotherapy.',
  ARRAY['therapeutic'],
  '134 F Street, Suite 201', 'Salida', 'CO', '81201',
  38.5357748, -105.9924906,
  '7197525672', 'https://wildrootstherapeutics.com', 'mamie@wildrootstherapeutics.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center); own site (wildrootstherapeutics.com) lists "Psilocybin Assisted Therapy" among its services. Street address from HAF directory.', 'basic',
  0, 0
),
(
  'micro-healing-center', 'Micro Healing Center', 'A licensed Colorado center in Westminster providing psychedelic-assisted therapy under Colorado''s Natural Medicine regulations.',
  ARRAY['therapeutic'],
  '8461 Turnpike Dr, Ste 110', 'Westminster', 'CO', '80031',
  39.8494486, -105.0491357,
  '3032845144', 'https://microhealingcenter.com', 'info@microhealingcenter.com',
  '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"10:00-18:00","sat":null,"sun":null}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "A licensed Colorado center providing psychedelic-assisted therapy" "Operating under Colorado''s Natural Medicine regulations" on microhealingcenter.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'mindful-elevation', 'Mindful Elevation Natural Medicine Healing Center', 'A lakefront Natural Medicine Healing Center in Evergreen offering legal psilocybin-assisted therapy guided by licensed facilitators, by appointment.',
  ARRAY['therapeutic'],
  '29029 Upper Bear Creek Rd, Suite 302-306', 'Evergreen', 'CO', '80439',
  39.6336562, -105.3299557,
  '2109946336', 'https://mindfulelevationhealingcenter.com', 'info@mindfulelevationhealingcenter.com',
  '{"mon":"By appointment","tue":"By appointment","wed":"By appointment","thu":"By appointment","fri":"By appointment","sat":"By appointment","sun":"By appointment"}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Self-described "a lakefront Natural Medicine Healing Center" offering "Legal Psilocybin Assisted Therapy" on mindfulelevationhealingcenter.com; listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center).', 'basic',
  0, 0
),
(
  'reflective-healing', 'Reflective Healing', 'A Fort Collins practice offering psilocybin-assisted therapy along with ketamine-assisted psychotherapy, psychedelic integration, and microdosing support.',
  ARRAY['therapeutic'],
  '605 S College Ave, Suite B100', 'Fort Collins', 'CO', '80524',
  40.5798891, -105.0768769,
  '9704490853', 'https://reflectivehealing.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  true, 'Listed on Healing Advocacy Fund active-licensee directory (healingadvocacyfund.org/co-healing-center); own site (reflectivehealing.com) lists "Psilocybin-Assisted Therapy" among its services. Own-site address (605 S College Ave) used in place of HAF''s 171 N College Ave listing.', 'basic',
  0, 0
),
(
  'hazel-dell-mushrooms', 'Hazel Dell Mushrooms', 'Family-owned mushroom farm operating in Colorado''s Northern Front Range since 1997, growing gourmet organic mushrooms (Lion''s Mane, King Oyster, Golden Oyster and more) sold fresh, dried and powdered at its on-site retail store.',
  ARRAY['gourmet'],
  '3925 E County Road 32', 'Fort Collins', 'CO', '80528',
  40.4795751, -105.0067459,
  NULL, 'https://hazeldellmushrooms.com', NULL,
  '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'mile-high-fungi', 'Mile High Fungi', 'Colorado gourmet mushroom farm growing sustainably-cultivated varieties (shiitake, blue & phoenix oyster, chestnut, pioppini, king trumpet, lion''s mane, maitake, beech) plus seasonal wild-foraged mushrooms; sold at Denver farmers markets and via CSA partners.',
  ARRAY['gourmet'],
  '19054 Gooseberry Lane', 'Littleton', 'CO', '80127',
  39.613321, -105.016649,
  '7204810770', 'https://www.milehighfungi.com', 'info@milehighfungi.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'furst-class-fungi', 'Furst Class Fungi', 'Denver-based gourmet mushroom farm selling fresh mushrooms at Colorado farmers markets (City Park, Lafayette, Old South Pearl St) and to local restaurants, with a winter CSA offering pickup and delivery.',
  ARRAY['gourmet'],
  '375 Zenobia St', 'Denver', 'CO', '80219',
  39.721868, -105.052353,
  '8607291177', 'https://www.furstclassfungi.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'elevated-mushrooms', 'Elevated Mushrooms', 'Englewood mushroom farm and lab growing gourmet and medicinal fungi (Lion''s Mane, King/Polar White/Grey Oyster, Chestnut, Black Pearl) with a storefront selling fresh mushrooms, supplements, cultivation supplies and gourmet treats.',
  ARRAY['gourmet', 'medicinal'],
  '4551 S Logan St', 'Englewood', 'CO', '80113',
  39.634019, -104.9832432,
  '3032492462', 'https://elevatedmushrooms.com', 'paul@elevatedmushrooms.net',
  '{"tue":"10:00-15:00","wed":"10:00-15:00","thu":"10:00-15:00","fri":"10:00-15:00","sat":"10:00-13:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'fox-fungi', 'Fox Fungi', 'Denver urban mushroom farm and retail storefront offering daily-restocked fresh gourmet mushrooms (including oyster varieties), functional mushroom powders, pantry items, frozen meals and mycology supplies.',
  ARRAY['gourmet', 'medicinal'],
  '2370 S Kalamath St Unit D', 'Denver', 'CO', '80223',
  39.673616, -105.0005056,
  '3036561230', 'https://www.foxfungi.com', 'contact@foxfungi.com',
  '{"mon":"12:00-18:00","tue":"12:00-18:00","wed":"12:00-18:00","thu":"12:00-18:00","fri":"10:00-19:00","sat":"10:00-19:00","sun":"14:00-17:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'high-balsam-farm', 'High Balsam Farm', 'One-acre urban farm in Lakewood growing gourmet and medicinal specialty mushrooms (oyster, lion''s mane, reishi, turkey tail, chestnut, enoki, pioppini) sold fresh and dried, with a weekly mushroom CSA (Thursday pickup), tours and cultivation classes.',
  ARRAY['gourmet', 'medicinal'],
  '720 Balsam St', 'Lakewood', 'CO', '80214',
  39.7391754, -105.0884425,
  '7206292171', 'https://www.highbalsamfarm.com', 'Bethlloyd7@gmail.com',
  '{"thu":"16:00-18:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'soss-mushrooms', 'SOSS Mushrooms', 'Denver functional-mushroom retailer offering dual-extracted organic mushroom tinctures and gummies (Lion''s Mane, Cordyceps, Turkey Tail and a 5-Mushroom Blend); in-person product sales by appointment.',
  ARRAY['medicinal'],
  '480 S Holly St', 'Denver', 'CO', '80246',
  39.707927, -104.9219662,
  '3038347673', 'https://www.sossmushrooms.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'mushroom-saloon', 'The Mushroom Saloon @ CBD Life', 'Colorado Springs wellness retail shop with a curated selection of functional mushrooms alongside hemp/CBD products and mushroom-cultivation supplies, plus classes; operates two storefront locations.',
  ARRAY['medicinal'],
  '826 E Fillmore St', 'Colorado Springs', 'CO', '80907',
  38.8741647, -104.810333,
  '7199008733', 'https://themushroomsaloon.com', 'coloradosbigdiscovery@gmail.com',
  '{"mon":"11:00-18:00","tue":"11:00-18:00","wed":"11:00-18:00","thu":"11:00-18:00","fri":"11:00-18:00","sat":"11:00-18:00","sun":"11:00-16:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'apothecary-tinctura', 'Apothecary Tinctura', 'Denver herbal apothecary and integrative healing practice carrying medicinal mushroom products (Chaga, Maitake, Reishi, Lion''s Mane, Turkey Tail) in tincture, capsule and dried forms, alongside herbs, teas and wellness services.',
  ARRAY['medicinal'],
  '2900 E 6th Ave', 'Denver', 'CO', '80206',
  39.72553, -104.953259,
  '3033991175', 'https://www.apothecarytinctura.com', 'connect@apothecarytinctura.com',
  '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"10:00-18:00","sat":"10:00-17:00","sun":"12:00-17:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'berry-fungi-farms', 'Berry Fungi Farms', 'Paonia farm on the Western Slope that sustainably and regeneratively cultivates boutique gourmet mushrooms (oyster and other varieties), sold fresh and dried alongside mushroom grow kits and medicinal mushroom tinctures and extracts.',
  ARRAY['gourmet', 'medicinal'],
  'Minnesota Creek Rd', 'Paonia', 'CO', '81428',
  38.8695808, -107.5260292,
  '7202888521', 'https://berryfungifarms.com', NULL,
  '{"mon":"11:00-15:00","tue":"11:00-15:00","wed":"11:00-15:00","thu":"11:00-15:00","fri":"11:00-15:00","sat":"11:00-15:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'mycolove-farm', 'Mycolove Farm', 'Longmont organic farm that grows and extracts functional mushroom tinctures at the fruiting-body stage (Reishi, Lion''s Mane, Turkey Tail, Cordyceps Militaris) using an alcohol-free, glycerine-based ultrasonic extraction method.',
  ARRAY['medicinal'],
  '1811 Lefthand Circle', 'Longmont', 'CO', '80501',
  40.1427235, -105.1226635,
  NULL, 'https://www.mycolove.farm', 'team@mycolove.farm',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'benevolence-orchard-gardens', 'Benevolence Orchard & Gardens', 'Boulder farm running an 8-week gourmet mushroom CSA (Lion''s Mane, Oyster, Pioppino, Chestnut, Shiitake and more) with pickup at its on-site Orchard Hub, open daily 10am to dusk on an honor system, alongside heirloom apples and seasonal farm goods.',
  ARRAY['gourmet'],
  '6712 Jay Rd', 'Boulder', 'CO', '80301',
  40.0498275, -105.1961804,
  '7209387708', 'https://www.benevolenceorchard.com', NULL,
  '{"mon":"10:00-19:00","tue":"10:00-19:00","wed":"10:00-19:00","thu":"10:00-19:00","fri":"10:00-19:00","sat":"10:00-19:00","sun":"10:00-19:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'alpine-valley-mushrooms', 'Alpine Valley Mushrooms', 'Family-operated certified-organic gourmet mushroom farm in the San Luis Valley (Saguache), established 2022, growing mushrooms on local Colorado grains and 100% locally sourced substrate; farm tours and consultations by appointment.',
  ARRAY['gourmet'],
  '319 San Juan Ave', 'Saguache', 'CO', '81149',
  38.0864024, -106.1361293,
  '3039162691', 'https://www.alpinevalleymushrooms.com', 'alpinevalleymushrooms@gmail.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'rebeccas-herbal-apothecary', 'Rebecca''s Herbal Apothecary & Supply', 'Boulder herbal apothecary on Spruce Street carrying medicinal mushroom products (Chaga, Cordyceps, Lion''s Mane, Reishi, Turkey Tail) in extract, powder, slice and dried forms, alongside bulk herbs, teas and herbalism supplies.',
  ARRAY['medicinal'],
  '1227 Spruce St', 'Boulder', 'CO', '80302',
  40.0192627, -105.2796848,
  '3034438878', 'https://www.rebeccasherbs.com', NULL,
  '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"10:00-18:00","sat":"11:00-17:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'orions-apothecary', 'Orion''s Apothecary & Mushrooms', 'Loveland apothecary offering handcrafted teas, tinctures, tonics and bulk herbs along with mushroom products, mushroom grow kits and mushroom-cultivation education classes.',
  ARRAY['medicinal'],
  '270 E 29th St', 'Loveland', 'CO', '80538',
  40.4217647, -105.0747876,
  '9706172996', 'https://www.orionsapothecary.com', 'info@orionsapothecary.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'balanced-root-apothecary', 'Balanced Root Apothecary', 'Capitol Hill, Denver herbal apothecary stocking medicinal mushroom products, including a Functional Mushroom Mix, within its "Mushrooms + Superfoods" line, alongside organic herbal remedies, tinctures and teas.',
  ARRAY['medicinal'],
  '1405 N Ogden St', 'Denver', 'CO', '80218',
  39.7336476, -104.9752875,
  '7202769006', 'https://www.balancedrootapothecary.com', 'hello@balancedrootapothecary.com',
  '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"09:00-18:00","sat":"09:00-17:00","sun":"09:00-17:00"}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'fungus-farm-colorado', 'Fungus Farm Colorado', 'Colorado Springs gourmet and medicinal mushroom farm growing fresh and dried mushrooms (oak-sawdust and soybean-hull substrate), selling mushroom grow kits and dual-extraction (hot water then alcohol) medicinal extracts and tinctures; farm pickup by appointment plus area farmers markets and retail partners.',
  ARRAY['gourmet', 'medicinal'],
  '5117 Half Moon Dr', 'Colorado Springs', 'CO', '80915',
  38.8643641, -104.7326395,
  NULL, 'https://www.fungusfarmcolorado.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, NULL, 'basic',
  0, 0
),
(
  'real-mushrooms', 'Real Mushrooms', 'Sells 100% mushroom-fruiting-body extract supplements (Lion''s Mane, Reishi, Cordyceps, Chaga, Turkey Tail, and the 5 Defenders blend) in powders and capsules for people and pets, with no grain fillers.',
  ARRAY['medicinal'],
  '330 5th Avenue SW, Tower 1, Suite 1800', 'Calgary', 'AB', 'T2P 0L4',
  51.0488256, -114.069204,
  '18002634387', 'https://www.realmushrooms.com', 'hello@realmushrooms.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'host-defense', 'Host Defense (Fungi Perfecti)', 'Paul Stamets'' mycelium-based mushroom supplement line (Lion''s Mane, Reishi, Turkey Tail, Chaga, Cordyceps, MyCommunity and other blends) sold as capsules, powders, gummies, extracts, sprays and drink mixes.',
  ARRAY['medicinal'],
  '', 'Olympia', 'WA', '98507',
  47.0451022, -122.8950075,
  '3604269292', 'https://fungi.com', 'info@fungi.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'freshcap-mushrooms', 'FreshCap Mushrooms', 'Organic functional-mushroom supplements (Lion''s Mane, Cordyceps, Reishi, Chaga, Turkey Tail, Tremella, Maitake, the Ultimate Mushroom Complex blend, and mushroom coffee) in capsules and powders, plus pet products.',
  ARRAY['medicinal'],
  '57-52343 Range Road 211', 'Sherwood Park', 'AB', 'T8G 1A6',
  53.5256963, -113.296631,
  '8558135808', 'https://www.freshcap.com', 'support@freshcap.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'four-sigmatic', 'Four Sigmatic', 'Functional-mushroom coffees, lattes, hot cocoa, protein and supplements featuring Lion''s Mane, Chaga, Cordyceps and Reishi.',
  ARRAY['medicinal'],
  '1450 2nd St, Suite 210', 'Santa Monica', 'CA', '90401',
  34.0136602, -118.4961426,
  '8554008584', 'https://us.foursigmatic.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'om-mushroom-superfood', 'Om Mushroom Superfood', 'Whole-food cultivated functional-mushroom powders, capsules, drink mixes and broths (Lion''s Mane, Reishi, Cordyceps, Chaga, Turkey Tail and blends).',
  ARRAY['medicinal'],
  '5931 Priestly Drive, Suite 101', 'Carlsbad', 'CA', '92008',
  33.1327084, -117.2731506,
  NULL, 'https://ommushrooms.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'nootropics-depot', 'Nootropics Depot', 'Online retailer of nootropics and supplements including lab-tested functional-mushroom extracts (Lion''s Mane, Reishi, Cordyceps, Chaga and others) in capsules and powders.',
  ARRAY['medicinal'],
  '8380 S Kyrene Rd, Suite 110', 'Tempe', 'AZ', '85284',
  33.3383851, -111.9457878,
  '4807790257', 'https://nootropicsdepot.com', NULL,
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'mushroom-revival', 'Mushroom Revival', 'USDA Organic functional-mushroom supplements in capsules, tinctures, powders and gummies (Lion''s Mane, Reishi, Cordyceps, Turkey Tail, Chaga and blends).',
  ARRAY['medicinal'],
  '301 West Ave, 5501', 'Austin', 'TX', '78701',
  30.2678018, -97.7511675,
  NULL, 'https://www.mushroomrevival.com', 'support@mushroomrevival.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'north-spore', 'North Spore', 'Mushroom cultivation supplies (spawn, grow kits, substrates) plus a wellness line of mushroom tinctures, capsules, mushroom coffee, chocolate and dried mushrooms.',
  ARRAY['medicinal'],
  '921 Riverside Street', 'Portland', 'ME', '04103',
  43.7062909, -70.3180425,
  '2073520264', 'https://northspore.com', 'info@northspore.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
),
(
  'troop', 'Troop', 'Functional-mushroom daily gummies and blends (Lion''s Mane, Reishi and the Super Troop multi-mushroom blend).',
  ARRAY['medicinal'],
  '', 'Los Angeles', 'CA', '',
  34.0536909, -118.242766,
  '4242349097', 'https://trytroop.com', 'info@trytroop.com',
  '{}'::jsonb,
  NULL, ARRAY[]::text[],
  false, 'online', 'basic',
  0, 0
);
